server:
  port: 11000

spring:
  datasource:
    username: root
    password: poco1024!
    url: jdbc:mysql://192.168.12.19:3306/gulimall_wms
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.12.19:8848
  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu: debug